fixing blastn_plus

diff --git a/package-lgtseek/bin/run_blast_plus b/package-lgtseek/bin/run_blast_plus
--- a/package-lgtseek/bin/run_blast_plus
+++ b/package-lgtseek/bin/run_blast_plus
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 if [ -z "$SCHEMA_DOCS_DIR" ]
 then
     SCHEMA_DOCS_DIR=
@@ -61,21 +61,21 @@ case $arg in
     --out)
     out="$val"
     ;;
-	--exclude_gi)
-	exclude_gi="${val:-0}"
-	;;
-	--gi_file)
-	gi_file="$val:-"
-	;;
+    --exclude_gi)
+    exclude_gi="${val:-0}"
+    ;;
+    --gi_file)
+    gi_file="$val:-"
+    ;;
     --other_opts)
     other_opts="$val"
 	;;
     --query)
     query="$val"
     ;;
-	--remote)
-	remote="${val:-0}"
-	;;
+    --remote)
+    remote="${val:-0}"
+    ;;
     --task)
     task="$val"
     ;;
@@ -105,7 +105,7 @@ if [ $remote -eq 0 ]; then
 	# Local version
     blast_plus_cmd="$blast_plus_cmd -outfmt 11 -out $out.asn -max_target_seqs $max_target_seqs"
 else
-	if [ $gi_file ]; then
+	if [ ! -z $gi_file ] && [ -f $gi_file ]; then
 		echo "Cannot use GI file to filter BLAST database in 'remote mode': Exiting" >&2
 		exit 1
 	fi
@@ -115,6 +115,8 @@ fi
 
 echo "$blast_plus_cmd"
 $blast_plus_cmd
+
+check_for_success $blast_plus_cmd $?
 
 # Time to run blast_formatter, either once or twice depending on -remote
 blast_fmtr_cmd="${blast_plus_bin}/blast_formatter"
@@ -127,8 +129,9 @@ if [ $remote -eq 0 ]; then
     $blast_pairwise_cmd
     echo "$blast_m8_cmd"
     $blast_m8_cmd
-	echo "Now removing ASN file"
-	`rm $out.asn`
+    check_for_success $blast_m8_cmd $?
+    echo "Now removing ASN file"
+    `rm $out.asn`
 else
 	# Remote
     RID=$(grep "RID" $out | cut -d' ' -f2 | head -1)
@@ -136,6 +139,7 @@ else
         blast_m8_cmd="$blast_fmtr_cmd -rid $RID -outfmt 6 -out $out.m8"
         echo "$blast_m8_cmd"
         $blast_m8_cmd
+        check_for_success $blast_m8_cmd $?
     else
         echo "Cannot obtain RID from BLAST+ remote pairwise output $out: Exiting" >&2
     	exit 1
@@ -143,3 +147,10 @@ else
 fi
 
 exit 0
+
+check_for_success() {
+    if [ $2 -ne 0 ]; then 
+        echo "$1 failed with exit code $2"
+        exit 1
+    fi
+}
